language: java
jdk: 
  - oraclejdk11
before_install:
  - sudo apt-get update
  - cd app/
  - echo "starging maven pkg"
  - mvn clean package
  - cd ..
  - echo "we have mvn pkg. Lets to docker folder"
script:
  - docker-compose build
before_deploy:
  echo $DOCKER_PASSWORD >> ~/pass.txt
  echo cat ~/pass.txt | docker login --username "$DOCKER_USERNAME" -- password-stdin
deploy:
  provider: script
  script: 
    docker tag docker-to-aws-with-java:latest rafaelrend/docker-to-aws-with-java:latest;
    docker push rafaelrend/docker-to-aws-with-java;
  on:
    branch: master
notifications:
  email: false